### ISSUE TITLE
[NOTICE] IMPORTANT - BREAKING REPOSITORY CHANGES

### ISSUE THREAD

**Issue by sudoforge** [sudoforge/docker-mumble-server#63]
In preparation for maintaining various docker images under a single repository, `bddenhartog/alpine-murmur` will be renamed to `containerly/docker-library`. Additionally, several structural changes will be applied (directories/files reorganized).

**Migration notes**

- On Docker Hub: The `bddenhartog/docker-murmur` and `bddenhartog/alpine-murmur` images will be removed on **MAY 1, 2017**, in favor of the new [`containerly/murmur`](https://hub.docker.com/r/containerly/murmur/) image, which is available now. All images are automatically built from the same source code, etc. **YOU SHOULD** update your scripts and custom images to pull from [`containerly/murmur`](https://hub.docker.com/r/containerly/murmur/) as soon as possible. Note that `containerly/murmur` follows a different versioning scheme, with 1:1 parity with Mumble/Murmur releases. Be sure to look at the available tags.

- This repository will see significant changes as the new folder hierarchy is implemented. If you have script(s) or process(es) which rely on the folder structure within this repository, please take the following changes into account:
    - `Dockerfile` will be moved to `library/murmur/Dockerfile`
    - `murmur/` and its contents will be moved to `library/murmur/config`
    - The `Makefile` in the root directory will be removed  
    - The `docker-murmur` executable will be moved and renamed to `library/murmur/docker-entrypoint.sh`

**Comment by bddenhartog** [comment]
`bddenhartog/docker-murmur` and `bddenhartog/alpine-murmur` have been removed from Docker Hub.

Please update your scripts and host machines to use `containerly/murmur`.

**Comment by bddenhartog** [comment]
Note that this will be reverted as I have dissolved the containerly organization.
