### ISSUE TITLE
An image should be added for an irc bouncer (weechat, znc, ...)

### ISSUE THREAD

**Issue by sudoforge** [sudoforge/docker-mumble-server#85]

**Comment by SISheogorath** [comment]
May have a look into https://octo.sh/MadIRC/weechat-docker if you don't want to build it from scratch.

**Comment by sudoforge** [comment]
Actually, this was to explore running it as a relay, not a client -- although I will likely be exploring using a remote client in e.g. k8s and sshing to it with `mosh`; there are a ton of preexisting client-focused images out there - thanks for the link to that one!

**Comment by sudoforge** [comment]
On a completely unrelated note, mounting `~/.weechat` into a container running weechat resets your config -- at least, it resets what it doesn't bork.

**Comment by sudoforge** [comment]
Closing this, as the repository has been refactored to support mumble-server only.
